services:
  mongodb:
    image: mongo
    container_name: hidden_door-app
    ports:
      - "27019:27017"
    volumes:
      - hidden_door:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}

volumes:
  hidden_door:
